### ISSUE TITLE
Reusabilty

### ISSUE THREAD

**Issue by errordeveloper** [erikh/box#25]
Essentially one of major limitation of Dockerfile for me had been that the only way to achieve reusability is to either write a shell script, or create an image. I cannot see any example of loading helper methods from another file, is it just like you'd expect it to work in Ruby or I'd have to do something special? (I wouldn't need gems, although would be nice to be able to share stuff, but local libraries would a great option).

**Comment by errordeveloper** [comment]
I found https://github.com/mattn/mruby-require and https://github.com/iij/mruby-require, are these usable with box? (Sorry if this sounds like a lazy question, I'd love to spend some time playing with box, it's mega awesome, but too busy at the moment, so please pardon me asking so impatiently).

**Comment by erikh** [comment]
oh it saw none of my replies! Thanks, github.

Here's a paste:

I have to add the feature. I'm torn on this one because it really does enable raising build plan complexity through the roof, but I've already been running into situations where this'd be super useful to implement.

I guess giving people the gun isn't so bad as long as we advise them in the docs.

A separate library is not necessary, there's a pr here: https://github.com/mitchellh/go-mruby/pull/15 this just needs to be merged and then a new "require" function would be created in builder/funcs.go which would enable this through the builder struct.

I can put this in a branch tonight if you want to play with it!

I realize now that with the `-o` flag people can just reject this functionality if it's not good for their org/principles/etc so let's just do it.

**Comment by errordeveloper** [comment]
> oh it saw none of my replies! Thanks, github.

I've noticed email replies not going through recently...

**Comment by errordeveloper** [comment]
> I guess giving people the gun isn't so bad as long as we advise them in the docs.

Well, it'd be just another one, they already can do anything on the container side and anything Ruby syntax allows...

**Comment by errordeveloper** [comment]
> I can put this in a branch tonight if you want to play with it!

No rush, I'm too busy until KubeCon.

**Comment by erikh** [comment]
That's not necessary, there's a pr here:
https://github.com/mitchellh/go-mruby/pull/15 this just needs to be merged
and then a new "require" function would be created in builder/funcs.go
which would enable this through the builder struct.

I can put this in a branch tonight if you want to play with it!

**Comment by erikh** [comment]
Closed by #27, let me know if you need anything else!
